In [2]:
import numpy as np

In [8]:
math=np.array([[0., 0., 9.9005], [0., 0., 9.9005], [0., 0., 9.9005], [0., 0., 
  9.9005], [0., 0., 9.9005], [0., 0., 9.9005], [0., 0., 9.9005], [0., 
  0., 9.9005], [0.2, 0., 16.6274], [0.141421, 0.141421, 
  8.16348], [1.22465e-17, 0.2, 2.27376], [-0.141421, 0.141421, 
  8.16348], [-0.2, 2.44929e-17, 16.6274], [-0.141421, -0.141421, 
  8.16348], [-3.67394e-17, -0.2, 2.27376], [0.141421, -0.141421, 
  8.16348], [0.4, 0., 16.3528], [0.282843, 0.282843, 
  8.09967], [2.44929e-17, 0.4, 0.524073], [-0.282843, 0.282843, 
  8.09967], [-0.4, 4.89859e-17, 16.3528], [-0.282843, -0.282843, 
  8.09967], [-7.34788e-17, -0.4, 0.524073], [0.282843, -0.282843, 
  8.09967], [0.6, 0., 13.6385], [0.424264, 0.424264, 
  6.7887], [3.67394e-17, 0.6, 0.192157], [-0.424264, 0.424264, 
  6.7887], [-0.6, 7.34788e-17, 13.6385], [-0.424264, -0.424264, 
  6.7887], [-1.10218e-16, -0.6, 0.192157], [0.424264, -0.424264, 
  6.7887], [0.8, 0., 10.3812], [0.565685, 0.565685, 
  5.17721], [4.89859e-17, 0.8, 0.0819604], [-0.565685, 0.565685, 
  5.17721], [-0.8, 9.79717e-17, 10.3812], [-0.565685, -0.565685, 
  5.17721], [-1.46958e-16, -0.8, 0.0819604], [0.565685, -0.565685, 
  5.17721], [1., 0., 7.27202], [0.707107, 0.707107, 
  3.62995], [6.12323e-17, 1., 0.0366774], [-0.707107, 0.707107, 
  3.62995], [-1., 1.22465e-16, 7.27202], [-0.707107, -0.707107, 
  3.62995], [-1.83697e-16, -1., 0.0366774], [0.707107, -0.707107, 
  3.62995], [1.2, 0., 4.69755], [0.848528, 0.848528, 
  2.34604], [7.34788e-17, 1.2, 0.0164356], [-0.848528, 0.848528, 
  2.34604], [-1.2, 1.46958e-16, 4.69755], [-0.848528, -0.848528, 
  2.34604], [-2.20436e-16, -1.2, 0.0164356], [0.848528, -0.848528, 
  2.34604], [1.4, 0., 2.80024], [0.989949, 0.989949, 
  1.39892], [8.57253e-17, 1.4, 0.00719276], [-0.989949, 0.989949, 
  1.39892], [-1.4, 1.71451e-16, 2.80024], [-0.989949, -0.989949, 
  1.39892], [-2.57176e-16, -1.4, 0.00719276], [0.989949, -0.989949,
   1.39892], [1.6, 0., 1.54081], [1.13137, 1.13137, 
  0.769897], [9.79717e-17, 1.6, 0.00302844], [-1.13137, 1.13137, 
  0.769897], [-1.6, 1.95943e-16, 1.54081], [-1.13137, -1.13137, 
  0.769897], [-2.93915e-16, -1.6, 0.00302844], [1.13137, -1.13137, 
  0.769897], [1.8, 0., 0.782696], [1.27279, 1.27279, 
  0.391144], [1.10218e-16, 1.8, 0.00121493], [-1.27279, 1.27279, 
  0.391144], [-1.8, 2.20436e-16, 0.782696], [-1.27279, -1.27279, 
  0.391144], [-3.30655e-16, -1.8, 0.00121493], [1.27279, -1.27279, 
  0.391144], [2., 0., 0.367079], [1.41421, 1.41421, 
  0.183462], [1.22465e-16, 2., 0.000461328], [-1.41421, 1.41421, 
  0.183462], [-2., 2.44929e-16, 0.367079], [-1.41421, -1.41421, 
  0.183462], [-3.67394e-16, -2., 0.000461328], [1.41421, -1.41421, 
  0.183462]])

In [5]:
eload = np.load('e.0.1.npz')

In [23]:
eload['e01']

array([[9.90049803e+00, 9.90049804e+00, 9.90049811e+00, 9.90049820e+00,
        9.90049829e+00, 9.90049833e+00, 9.90049832e+00, 9.90049825e+00,
        9.90049816e+00, 9.90049807e+00, 9.90049803e+00, 9.90049804e+00,
        9.90049811e+00, 9.90049820e+00, 9.90049829e+00, 9.90049833e+00,
        9.90049832e+00, 9.90049825e+00, 9.90049816e+00, 9.90049807e+00],
       [1.66274023e+01, 1.49984630e+01, 1.07545932e+01, 5.64103381e+00,
        2.42941843e+00, 2.27375910e+00, 2.42941841e+00, 5.64103377e+00,
        1.07545931e+01, 1.49984630e+01, 1.66274023e+01, 1.49984630e+01,
        1.07545932e+01, 5.64103381e+00, 2.42941843e+00, 2.27375910e+00,
        2.42941841e+00, 5.64103377e+00, 1.07545931e+01, 1.49984630e+01],
       [1.63527804e+01, 1.47760116e+01, 1.06489340e+01, 5.55331824e+00,
        1.48202624e+00, 5.24073284e-01, 1.48202624e+00, 5.55331823e+00,
        1.06489340e+01, 1.47760116e+01, 1.63527804e+01, 1.47760116e+01,
        1.06489340e+01, 5.55331824e+00, 1.48202624e+00, 5.2407

In [29]:
f = open('t01.dat')

In [37]:
f.seek(0)
math=np.array([float(e) for e in f.read().split('\n')])

In [38]:
f.close()

In [39]:
math

array([9.90049834e+00, 9.90049834e+00, 9.90049834e+00, 9.90049834e+00,
       9.90049834e+00, 9.90049834e+00, 9.90049834e+00, 9.90049834e+00,
       9.90049834e+00, 9.90049834e+00, 9.90049834e+00, 9.90049834e+00,
       9.90049834e+00, 9.90049834e+00, 9.90049834e+00, 9.90049834e+00,
       9.90049834e+00, 9.90049834e+00, 9.90049834e+00, 9.90049834e+00,
       1.66274026e+01, 1.49984633e+01, 1.07545932e+01, 5.64103174e+00,
       2.42940844e+00, 2.27375910e+00, 2.42941846e+00, 5.64102550e+00,
       1.07546226e+01, 1.49984834e+01, 1.66274026e+01, 1.49984834e+01,
       1.07546226e+01, 5.64102550e+00, 2.42941846e+00, 2.27375910e+00,
       2.42940844e+00, 5.64103174e+00, 1.07545932e+01, 1.49984633e+01,
       1.63527806e+01, 1.47760119e+01, 1.06489342e+01, 5.55331834e+00,
       1.48202627e+00, 5.24073284e-01, 1.48202627e+00, 5.55331834e+00,
       1.06489342e+01, 1.47760119e+01, 1.63527806e+01, 1.47760119e+01,
       1.06489342e+01, 5.55331834e+00, 1.48202627e+00, 5.24073284e-01,
      

In [42]:
np.sum(np.abs(np.reshape(eload['e01'], np.prod(np.array(eload['e01'].shape)))/math-1))

2.3391551890683537e-05

In [49]:
eload = np.load('e.2.npz')

In [44]:
f = open('t2.dat')

In [45]:
f.seek(0)
math2=np.array([float(e) for e in f.read().split('\n')])
f.close()

In [56]:
np.sum(np.abs(np.reshape(eload['e2'], np.prod(np.array(eload['e2'].shape)))/math2-1))

2.167730230110055

In [62]:
np.reshape(eload['e2'], np.prod(np.array(eload['e2'].shape)))/math2-1<0.1

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [3]:
eload = np.load('e.4.npz')

In [5]:
f = open('t4.dat')
f.seek(0)
math4=np.array([float(e) for e in f.read().split('\n')])
f.close()

In [8]:
np.reshape(eload['e4'], np.prod(np.array(eload['e4'].shape)))/math4-1<0.3

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,