In [1]:
import sys
sys.path.append('../Code/')
from initcond import *
import numpy as np
from lattice import *
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import time

In [9]:
np.__file__

'/Users/biwu/miniconda3/lib/python3.7/site-packages/numpy/__init__.py'

# The gaussian profile

In [2]:
ic = InitCond('gaussian', 0.1, (2, 1.0), (3, 1.0), (4, 1.0), (5, 1.0))

In [3]:
ic.FTn(1.0, 0.3)

array([0.91566319-0.05989967j, 0.54929434-0.05399577j,
       0.27939941-0.03671188j, 0.12543446-0.02066866j])

# The background

In [4]:
latt = Lattice(('r tilde', 0.0, 3.0, 31),
                ('vz tilde', 0.0, 10.0, 21),
                ('phir', 40),
                ('theta', 10))
print(latt)
print(latt.lattice)

Description: ['r tilde', 'vz tilde', 'phir', 'theta']
Shape: [31, 21, 40, 10]
[array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. ]), array([0.        , 0.24491866, 0.46211716, 0.63514895, 0.76159416,
       0.84828364, 0.90514825, 0.94137554, 0.96402758, 0.97802611,
       0.9866143 , 0.99185972, 0.99505475, 0.99699764, 0.9981779 ,
       0.99889444, 0.9993293 , 0.99959315, 0.99975321, 0.99985031,
       0.9999092 ]), array([1.00000000e-07, 1.57079733e-01, 3.14159365e-01, 4.71238998e-01,
       6.28318631e-01, 7.85398263e-01, 9.42477896e-01, 1.09955753e+00,
       1.25663716e+00, 1.41371679e+00, 1.57079643e+00, 1.72787606e+00,
       1.88495569e+00, 2.04203532e+00, 2.19911496e+00, 2.35619459e+00,
       2.51327422e+00, 2.67035386e+00, 2.82743349e+00, 2.98451312e+00,
       3.14159275e+00, 3.29867239e+00, 3.45575202e+00, 3.61283165e+00,
       3.76991128e+00, 3.926

In [5]:
ic = InitCond('gaussian', 0.1, (2, 0.0))

In [6]:
ic.Fbg(0.1, 0.3)

19.98214257259169

It agrees with the result in 'initcond.nb'.

# The full distribution

In [7]:
ic.Fn(0.1, 0.2, 0.3)

array([0.93890381])

In [8]:
print(latt)

Description: ['r tilde', 'vz tilde', 'phir', 'theta']
Shape: [31, 21, 40, 10]


In [9]:
ic = InitCond('gaussian', 0.1, (2, 1.0))

((2, 1.0),)


In [10]:
latt.lattice

[array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
        1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
        2.6, 2.7, 2.8, 2.9, 3. ]),
 array([0.        , 0.24491866, 0.46211716, 0.63514895, 0.76159416,
        0.84828364, 0.90514825, 0.94137554, 0.96402758, 0.97802611,
        0.9866143 , 0.99185972, 0.99505475, 0.99699764, 0.9981779 ,
        0.99889444, 0.9993293 , 0.99959315, 0.99975321, 0.99985031,
        0.9999092 ]),
 array([1.00000000e-07, 1.57079733e-01, 3.14159365e-01, 4.71238998e-01,
        6.28318631e-01, 7.85398263e-01, 9.42477896e-01, 1.09955753e+00,
        1.25663716e+00, 1.41371679e+00, 1.57079643e+00, 1.72787606e+00,
        1.88495569e+00, 2.04203532e+00, 2.19911496e+00, 2.35619459e+00,
        2.51327422e+00, 2.67035386e+00, 2.82743349e+00, 2.98451312e+00,
        3.14159275e+00, 3.29867239e+00, 3.45575202e+00, 3.61283165e+00,
        3.76991128e+00, 3.92699092e+00, 4.08407055e+00, 4.24115018e+00,
        4.39822982e+0

In [11]:
ic.gausstheta(latt)[1,0,1,1]*latt.lattice[1][1]

16.867158903606086

In [12]:
ic.gausstheta(latt)[4,0,1,1]*latt.lattice[1][1]

10.917499638042067

# Comparison

In [13]:
lattm = Lattice(('theta', 8), ('vz tilde', 0.0, 15.0, 11), ('r tilde', 0.0, 5.0, 13),
                ('phir', 5))
ic = InitCond('gaussian', 0.1, (2, 1.0))

((2, 1.0),)


In [14]:
lattm.lattice

[array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265,
        3.92699082, 4.71238898, 5.49778714]),
 array([0.        , 0.63514895, 0.90514825, 0.97802611, 0.99505475,
        0.99889444, 0.99975321, 0.99994493, 0.99998771, 0.99999726,
        0.99999939]),
 array([0.        , 0.41666667, 0.83333333, 1.25      , 1.66666667,
        2.08333333, 2.5       , 2.91666667, 3.33333333, 3.75      ,
        4.16666667, 4.58333333, 5.        ]),
 array([1.00000000e-07, 1.25663716e+00, 2.51327422e+00, 3.76991128e+00,
        5.02654835e+00])]

In [15]:
F0 = ic.gausstheta(lattm)

In [29]:
f = open('F0.dat')

In [30]:
f.seek(0)
a = f.read().replace('\t',',').replace('\n',',').replace('{','').replace('}','').replace(' ','').replace('*^','e').split(',')
F0math = np.reshape(np.array([float(num) for num in a]), lattm.shape)

In [31]:
np.sum(np.abs(F0math - F0))

1.195115119084197e-12

In [32]:
f.close()

# FFT

In [2]:
lattm = Lattice(('theta', 8), ('vz tilde', 0.0, 15.0, 11), ('r tilde', 0.0, 5.0, 13),
                ('phir', 5))
ic = InitCond('gaussian', 0.1, (2, 1.0))

((2, 1.0),)


In [3]:
F0 = ic.gauss(lattm)
F0.shape

(5, 11, 13, 5)

In [4]:
np.exp(-2.0j*lattm.lattice[3])

array([ 1.        -2.00000000e-07j, -0.80901711-5.87785090e-01j,
        0.30901718+9.51056454e-01j,  0.3090168 -9.51056578e-01j,
       -0.80901688+5.87785414e-01j])

In [5]:
F0fft = ic.gaussfft(lattm)
F0fft.shape

(5, 11, 13, 5)

In [6]:
from observable import *

In [7]:
t0 = 0.1
ob = Observable(t0, lattm)

In [8]:
ob.setTime(t0)

In [9]:
ob.calcphir()

In [10]:
np.sum(np.abs(ob.phir[:5, :, :, :]*F0 - F0fft))

1.199143397990292e-12