In [1]:
import sys
sys.path.append('../code/')
from observable import *

# 1. Interpolation

In [2]:
xti, yti, phi, vzti, t, t0 = 1.0, 0.5, 0.3, 0.1, 2.0, 0.1
ob = Observable(t0)
ob.setTime(t)

In [3]:
F = np.array([[[[1.0, 2.0],[3.0,1.5]],[[3.0, 1.5],[1.0, 2.0]]], [[[10.0, 2.0],[3.0,15]],[[9.0, 1.5],[8.0, 2.0]]]])

In [4]:
F.shape

(2, 2, 2, 2)

In [5]:
phi = np.array([0, 0.5])
rt = np.array([0, 2.0])

In [6]:
print(phi)
print(rt)

[0.  0.5]
[0. 2.]


In [7]:
ob.interpExt(F, rt, phi)

In [8]:
print(ob.Finterp[0][0](0.2, 0.1))
print(ob.Finterp[0][1](0.2, 0.1))
print(ob.Finterp[1][0](0.2, 0.1))
print(ob.Finterp[1][1](0.2, 0.1))

[1.35]
[2.55]
[8.1]
[7.43]


The same as Mathematica.

In [9]:
print(ob.Finterp[0][0](0.2, 1))
print(ob.Finterp[0][1](0.2, 1))
print(ob.Finterp[1][0](0.2, 1))
print(ob.Finterp[1][1](0.2, 1))

[0.]
[0.]
[0.]
[0.]


Different from Mathmatica!

In [10]:
for i in range(len(rt)):
    for j in range(len(phi)):
        print('({}, {}) = {} vs {}'.format(rt[i], phi[j], ob.Finterp[0][0](rt[i], phi[j]), F[0, 0, i, j]))

(0.0, 0.0) = [1.] vs 1.0
(0.0, 0.5) = [2.] vs 2.0
(2.0, 0.0) = [3.] vs 3.0
(2.0, 0.5) = [1.5] vs 1.5


In [11]:
#rr, pp = np.meshgrid(rt, phi)

In [12]:
#print('{}->{}'.format(rt, rr))
#print('{}->{}'.format(phi, pp))

In [11]:
r00 = np.array([[ob.Finterp[0][0](r, p)[0] for p in np.linspace(phi[0],phi[-1],6)] for r in np.linspace(rt[0], rt[-1], 21)])
#r00 = np.array([[ob.F(0, 0, r, p) for p in np.linspace(phi[0],phi[-1],6)] for r in np.linspace(rt[0], rt[-1], 21)])

In [12]:
r00math = [[1., 1.2, 1.4, 1.6, 1.8, 2.], [1.1, 1.2750000000000001, 
  1.45, 1.625, 1.8, 1.975], [1.2, 1.3499999999999999, 1.5, 
  1.65, 1.8, 1.95], [1.3, 1.425, 1.5499999999999998, 1.675, 
  1.8, 1.925], [1.4, 1.5, 1.5999999999999999, 1.7, 1.8, 
  1.9], [1.5, 1.575, 1.65, 1.725, 1.8, 1.875], [1.6, 
  1.6500000000000001, 1.7, 1.75, 1.8, 
  1.85], [1.7000000000000002, 1.725, 1.75, 1.775, 1.8, 
  1.825], [1.8, 1.8, 1.7999999999999998, 1.7999999999999998, 
  1.8, 1.8], [1.9, 1.875, 1.8499999999999999, 
  1.8249999999999997, 1.8, 1.775], [2., 1.9500000000000002, 1.9,
   1.8499999999999999, 1.7999999999999998, 1.75], [2.1, 
  2.0250000000000004, 1.95, 1.8749999999999998, 
  1.7999999999999998, 1.725], [2.2, 2.1, 2., 1.9, 
  1.7999999999999998, 1.7], [2.3, 2.1750000000000003, 2.05, 
  1.9249999999999998, 1.7999999999999998, 
  1.675], [2.4000000000000004, 2.25, 2.1, 1.9499999999999997, 
  1.7999999999999998, 1.65], [2.5, 2.325, 2.15, 
  1.9749999999999996, 1.7999999999999998, 1.625], [2.6, 
  2.4000000000000004, 2.2, 1.9999999999999998, 1.7999999999999998,
   1.6], [2.7, 2.475, 2.25, 2.025, 1.7999999999999998, 
  1.575], [2.8, 2.5500000000000003, 2.3, 2.05, 
  1.7999999999999998, 1.55], [2.9000000000000004, 
  2.6250000000000004, 2.35, 2.0749999999999997, 
  1.7999999999999998, 1.525], [3., 2.7, 2.4, 2.0999999999999996,
   1.7999999999999998, 1.5]]

In [13]:
r00.shape

(21, 6)

In [14]:
r00 - r00math

array([[ 0.00000000e+00,  2.22044605e-16,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  2.22044605e-16,
         0.00000000e+00,  0.00000000e+00, -2.22044605e-16],
       [ 2.22044605e-16,  2.22044605e-16,  2.22044605e-16,
         2.22044605e-16,  2.22044605e-16,  2.22044605e-16],
       [ 0.00000000e+00,  0.00000000e+00,  2.22044605e-16,
        -2.22044605e-16,  2.22044605e-16,  0.00000000e+00],
       [ 2.22044605e-16,  4.44089210e-16,  4.44089210e-16,
         2.22044605e-16,  0.00000000e+00,  2.22044605e-16],
       [ 0.00000000e+00,  2.22044605e-16,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  2.22044605e-16,
         0.00000000e+00, -2.22044605e-16,  0.00000000e+00],
       [-2.22044605e-16, -2.22044605e-16,  0.00000000e+00,
         0.00000000e+00, -2.22044605e-16, -2.22044605e-16],
       [ 2.22044605e-16,  2.22044605e-16,  2.220

In [14]:
np.sum(np.abs(r00 - r00math))

1.4210854715202004e-14

In [15]:
r01 = np.array([[ob.Finterp[0][1](r, p)[0] for p in np.linspace(phi[0],phi[-1],6)] for r in np.linspace(rt[0], rt[-1], 21)])

In [16]:
r01math = np.array([[3., 2.7, 2.4, 2.0999999999999996, 1.7999999999999998, 
  1.5], [2.9, 2.625, 2.3499999999999996, 2.0749999999999997, 
  1.7999999999999998, 1.525], [2.8, 2.5500000000000003, 2.3, 
  2.05, 1.7999999999999998, 1.55], [2.7, 2.475, 2.25, 
  2.0249999999999995, 1.7999999999999998, 1.575], [2.6, 
  2.4000000000000004, 2.2, 1.9999999999999998, 1.7999999999999998,
   1.6], [2.5, 2.325, 2.15, 1.9749999999999996, 
  1.7999999999999998, 1.625], [2.4, 2.25, 2.0999999999999996, 
  1.9499999999999997, 1.7999999999999998, 1.65], [2.3, 2.175, 
  2.05, 1.9249999999999998, 1.7999999999999998, 1.675], [2.2, 
  2.1, 2., 1.9, 1.7999999999999998, 1.7], [2.1, 
  2.0250000000000004, 1.95, 1.875, 1.7999999999999998, 
  1.725], [2., 1.9500000000000002, 1.9, 1.8499999999999999, 
  1.7999999999999998, 1.75], [1.9, 1.875, 1.8499999999999999, 
  1.825, 1.8, 1.775], [1.7999999999999998, 1.7999999999999998, 
  1.7999999999999998, 1.7999999999999998, 1.8, 1.8], [1.7, 
  1.725, 1.75, 1.775, 1.8, 1.825], [1.5999999999999999, 1.65, 
  1.6999999999999997, 1.75, 1.8, 1.85], [1.5, 1.575, 1.65, 
  1.725, 1.8, 1.875], [1.4, 1.5, 1.5999999999999999, 1.7, 1.8,
   1.9], [1.2999999999999998, 1.4249999999999998, 
  1.5499999999999998, 1.675, 1.8, 1.925], [1.2, 
  1.3499999999999999, 1.5, 1.6500000000000001, 1.8, 
  1.95], [1.0999999999999999, 1.275, 1.4499999999999997, 1.625, 
  1.8, 1.975], [1., 1.2, 1.4, 1.6, 1.8, 2.]])

In [17]:
np.sum(np.abs(r01 - r01math))

1.3766765505351941e-14

In [18]:
r10 = np.array([[ob.Finterp[1][0](r, p)[0] for p in np.linspace(phi[0],phi[-1],6)] for r in np.linspace(rt[0], rt[-1], 21)])

In [19]:
r10math = np.array([[10., 8.4, 6.8, 5.199999999999999, 3.5999999999999996, 
  2.], [9.649999999999999, 8.25, 6.85, 5.449999999999999, 
  4.050000000000001, 2.6500000000000004], [9.3, 8.1, 6.9, 
  5.699999999999999, 4.5, 3.299999999999999], [8.95, 7.95, 6.95,
   5.949999999999999, 4.95, 
  3.950000000000001], [8.600000000000001, 7.800000000000001, 7., 
  6.199999999999999, 5.3999999999999995, 4.6], [8.25, 7.65, 
  7.05, 6.449999999999999, 5.85, 5.25], [7.8999999999999995, 
  7.5, 7.1, 6.7, 6.300000000000001, 5.9], [7.549999999999999, 
  7.35, 7.15, 6.95, 6.750000000000001, 6.550000000000001], [7.2,
   7.199999999999999, 7.2, 7.2, 7.2, 7.2], [6.8500000000000005, 
  7.05, 7.25, 7.449999999999999, 7.65, 7.85], [6.5, 
  6.8999999999999995, 7.300000000000001, 7.7, 8.100000000000001, 
  8.5], [6.1499999999999995, 6.749999999999999, 
  7.3500000000000005, 7.950000000000001, 8.55, 
  9.15], [5.799999999999999, 6.599999999999999, 7.4, 
  8.200000000000001, 9.000000000000002, 9.8], [5.449999999999999, 
  6.449999999999999, 7.45, 8.450000000000001, 9.450000000000001, 
  10.45], [5.1, 6.299999999999999, 7.500000000000001, 
  8.700000000000001, 9.900000000000002, 
  11.100000000000001], [4.75, 6.149999999999999, 
  7.550000000000001, 8.950000000000001, 10.350000000000001, 
  11.75], [4.3999999999999995, 5.999999999999999, 
  7.6000000000000005, 9.200000000000001, 10.8, 
  12.4], [4.049999999999999, 5.849999999999999, 7.65, 
  9.450000000000001, 11.250000000000002, 
  13.05], [3.6999999999999997, 5.699999999999998, 
  7.700000000000001, 9.700000000000001, 11.700000000000001, 
  13.7], [3.3499999999999996, 5.549999999999998, 
  7.750000000000001, 9.950000000000001, 12.150000000000002, 
  14.350000000000001], [3., 5.399999999999999, 7.800000000000001, 
  10.200000000000001, 12.600000000000001, 15.]])

In [20]:
np.sum(np.abs(r10 - r10math))

6.128431095930864e-14

In [21]:
r11 = np.array([[ob.Finterp[1][1](r, p)[0] for p in np.linspace(phi[0],phi[-1],6)] for r in np.linspace(rt[0], rt[-1], 21)])

In [22]:
r11math = np.array([[9., 7.5, 6., 4.499999999999999, 2.9999999999999996, 
  1.5], [8.95, 7.465, 5.98, 4.494999999999999, 3.01, 
  1.525], [8.9, 7.43, 5.96, 4.489999999999999, 
  3.0199999999999996, 1.55], [8.85, 7.3950000000000005, 
  5.9399999999999995, 4.484999999999999, 3.0299999999999994, 
  1.575], [8.8, 7.36, 5.92, 4.4799999999999995, 
  3.0399999999999996, 1.6], [8.75, 7.325, 5.9, 4.475, 3.05, 
  1.625], [8.7, 7.29, 5.88, 4.469999999999999, 
  3.0599999999999996, 1.65], [8.65, 7.255, 5.859999999999999, 
  4.464999999999999, 3.07, 1.675], [8.6, 7.220000000000001, 
  5.84, 4.459999999999999, 3.0799999999999996, 1.7], [8.55, 
  7.1850000000000005, 5.82, 4.454999999999999, 3.0899999999999994,
   1.725], [8.5, 7.15, 5.8, 4.449999999999999, 
  3.0999999999999996, 1.75], [8.45, 7.115, 5.779999999999999, 
  4.444999999999999, 3.11, 1.775], [8.4, 7.08, 5.76, 
  4.4399999999999995, 3.1199999999999997, 1.8], [8.35, 
  7.045000000000001, 5.74, 4.435, 3.13, 1.825], [8.3, 
  7.010000000000001, 5.72, 4.43, 3.1399999999999997, 
  1.85], [8.25, 6.9750000000000005, 5.699999999999999, 
  4.424999999999999, 3.1499999999999995, 1.875], [8.2, 6.94, 
  5.68, 4.419999999999999, 3.1599999999999997, 1.9], [8.15, 
  6.905, 5.659999999999999, 4.414999999999999, 3.17, 
  1.925], [8.1, 6.870000000000001, 5.64, 4.409999999999999, 
  3.1799999999999997, 1.95], [8.05, 6.835000000000001, 
  5.619999999999999, 4.404999999999999, 3.19, 1.975], [8., 
  6.800000000000001, 5.6, 4.3999999999999995, 3.1999999999999997, 
  2.]])

In [23]:
np.sum(np.abs(r10 - r10math))

6.128431095930864e-14

# 2. Integrator

In [1]:
import sys
sys.path.append('../code/')
from lattice import *
from observable import *
import numpy as np
import timeit

In [2]:
latt = Lattice(('theta', 10), ('vz tilde', 0.0, 15.0, 121),
                ('r tilde', 0.0, 5.0, 201), ('phir', 40))

In [3]:
f = np.exp(-np.cos(latt.lattice[3])*np.cos(latt.lattice[3]))
print(f)

[0.36787944 0.37699316 0.40474079 0.45208162 0.51969748 0.60653072
 0.70787241 0.81374576 0.90892614 0.97582529 1.         0.97582523
 0.90892603 0.81374563 0.70787228 0.6065306  0.51969738 0.45208154
 0.40474074 0.37699314 0.36787944 0.37699316 0.40474079 0.45208162
 0.51969748 0.60653072 0.70787241 0.81374576 0.90892614 0.97582529
 1.         0.97582523 0.90892603 0.81374563 0.70787228 0.6065306
 0.51969738 0.45208154 0.40474074 0.37699314]


In [4]:
ob = Observable(0.1, latt)

<b>Time for the loops:</b>

In [5]:
start = timeit.default_timer()
for i in range(1000000):
    a = 1
timeit.default_timer()-start

0.07822334500000494

<font color="#ff0000">10 times faster than Mathematica!</font>

In [6]:
fr = np.exp(-latt.lattice[2]**2)
start = timeit.default_timer()
res = ob.drIntegrator(fr)
print(timeit.default_timer()-start, res)

0.00022710400000391928 0.49994791340399436


<font color="#ff0000">Comparable to Mathematica!</font>

In [7]:
f = np.exp(-np.cos(latt.lattice[1])*np.cos(latt.lattice[1]))
start = timeit.default_timer()
res = ob.dvIntegrator(f)
print(timeit.default_timer()-start, res)

0.00011903600000096048 0.49578717019302376


NIntegrate in Mathematica gives <font color='red'> 0.49565406681791935`.</font> 

In [8]:
f = np.exp(-np.cos(latt.lattice[ob.idx_ph])*np.cos(latt.lattice[ob.idx_ph]))
start = timeit.default_timer()
res = ob.dphiIntegrator(f)
print(timeit.default_timer()-start, res)

0.00011765500000393558 0.6450352645216424


Mathematica is 2 times slower because it only take half values of $\phi$.

In [24]:
A = np.array([[1.0, 0.15, 0.2],
            [-0.15, 0.25, 0.1],
            [-0.2, 0.1, 0.35]])

In [30]:
start = timeit.default_timer()
for i in range(10**5):
    e, u = np.linalg.eig(A)
print(timeit.default_timer()-start)

3.6948224170000685


In [33]:
print(e,u)

[0.8613406 0.55      0.1886594] [[ 0.87440657  0.48507125  0.02060349]
 [-0.2794288  -0.48507125 -0.83815885]
 [-0.39665185 -0.72760688  0.54503691]]


In [31]:
0.38183879300004264/0.140273

2.7221118319280446

<font color="#880088"><b> It is about 3 times slower than Mathmatica!</b></font>

# 3. $T^{\mu\nu}$

In [9]:
import sys
sys.path.append('../code/')
from lattice import *
from observable import *
import numpy as np
from initcond import *

In [10]:
latt = Lattice(('r tilde', 0.0, 5.0, 201),
                ('vz tilde', 0.0, 15.0, 121),
                ('phir', 40),
                ('theta', 10))

In [11]:
t0, t = 0.1, 1.0
ob = Observable(t0, latt)
ob.setTime(t)
ic = InitCond('gaussian', t0, (2, 0.0))

In [12]:
F= ic.gauss(latt)
ob.interp(F)

## 3.1 Test the integrand

In [13]:
print(ob.TuuIntegrand(0, 3.0, 0, 0))
print(ob.TuuIntegrand(0, 1.0, 0, 0))

[5.86863397e+01+0.j 5.86863397e+01+0.j 5.86863397e-06+0.j
 5.86863397e+01+0.j 5.86863397e-06+0.j 5.86863397e-13+0.j]
[3.20416558e+03+0.j 3.20416558e+03+0.j 3.20416558e-04+0.j
 3.20416558e+03+0.j 3.20416558e-04+0.j 3.20416558e-11+0.j]


In [14]:
print(ob.idx_v)
print(ob.idx_ph)

1
2


In [15]:
r = 1.0
r1 = np.array([[ob.TuuIntegrand(0, 1.0, i, j) for j in range(len(latt.lattice[ob.idx_ph]))] for i in range(len(latt.lattice[ob.idx_v]))])

In [16]:
f = open('Tuu.dat')

FileNotFoundError: [Errno 2] No such file or directory: 'Tuu.dat'

In [10]:
f.seek(0)
a = f.read().replace('\t',',').replace('\n',',').replace('{','').replace('}','').replace(' ','').replace('*^','e').split(',')

In [11]:
tuumath = np.reshape(np.array([float(num) for num in a]), [len(latt.lattice[ob.idx_v]), len(latt.lattice[ob.idx_ph]),4])

In [12]:
np.sum(np.abs(np.array([[[tuumath[i, j, 0] - r1[i, j, 0], tuumath[i, j, 1] - r1[i, j, 1],
            0.5*(tuumath[i, j, 2] + tuumath[i, j, 3]) - r1[i, j, 3],
            0.5*(tuumath[i, j, 2] - tuumath[i, j, 3]) - r1[i, j, 5]
           ] for j in range(len(latt.lattice[ob.idx_ph]))] for i in range(len(latt.lattice[ob.idx_v]))])))

3.5027536777950496e-12

In [6]:
ob.TuuIntegrand(0, 1.0, 0, 0)

array([320.4165582, 320.4165582,   0.       , 320.4165582,   0.       ,
         0.       ])

## 3.2 Test $T^{\mu\nu}$

In [5]:
tuu = ob.Tuu(0.1,0.1)

In [11]:
np.array([tuu[0], tuu[1], (tuu[3] + tuu[5]), (tuu[3] - tuu[5])]) - np.array([3.68065104342643, 0.36610391244692897, 3.68065104342643, \
0.01802602221906938])

array([ 0.00000000e+00, -1.66533454e-16,  4.44089210e-16, -3.12250226e-17])

In [5]:
ob.Tuu(0.1,0.1)

(40, 121, 6, 6)


array([[ 3.68065104e+00,  3.66103912e-01,  1.62939720e-17,
         0.00000000e+00],
       [ 3.66103912e-01,  1.84933853e+00,  2.42643179e-17,
         0.00000000e+00],
       [ 1.62939720e-17,  2.42643179e-17,  1.83131251e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -2.22044605e-16]])

## 3.3 Test RestFrame

In [6]:
ob.RestFrame(1,0.1)

(1, 0.1)
[-1.90013247  0.82337142  1.07676106]
[[-8.75962808e-01  4.82378646e-01  1.06042003e-16]
 [-4.82378646e-01  8.75962808e-01  1.69180533e-16]
 [-1.73012049e-17  3.14176677e-17  1.00000000e+00]]
u =  [[-1.19801535e+00]
 [-6.59727807e-01]
 [-2.36620879e-17]]


(0.1900132470924937, array([1.19801535e+00, 6.59727807e-01, 2.36620879e-17]))

In [7]:
ob.RestFrame(2,0.1)

(2, 0.1)
[-0.25275776  0.08830592  0.16445184]
[[-7.90904014e-01  6.11940227e-01 -3.09976420e-16]
 [-6.11940227e-01  7.90904014e-01 -5.17046917e-16]
 [-4.92722061e-17  6.36820131e-17  1.00000000e+00]]
u =  [[-1.57847051e+00]
 [-1.22129814e+00]
 [-9.83364896e-17]]


(0.02527577573882217, array([1.57847051e+00, 1.22129814e+00, 9.83364896e-17]))

### A test of np.linalg.eig:

In [8]:
A = np.array([[1,2],[3,4]])

In [11]:
ei, ev = np.linalg.eig(A)

In [13]:
np.dot(A, ev[:, 0])/ei[0]-ev[:, 0]

array([ 0.00000000e+00, -2.22044605e-16])

In [14]:
np.dot(A, ev[:, 1])/ei[1]-ev[:, 1]

array([-5.55111512e-17,  0.00000000e+00])

In [7]:
t0, t = 0.1, 1.0
ob = Observable(t0, latt)
ob.setTime(t)
ic = InitCond('gaussian', t0, (2, 1.0))

((2, 1.0),)


In [8]:
F= ic.gauss(latt)
ob.interp(F)

In [9]:
ob.RestFrame(1,0.1)

[[-6.64825513e+00  2.64641429e+00  1.03147172e-16]
 [-2.64641429e+00  3.21207379e+00  3.59970746e-17]
 [-1.03147172e-16  3.59970746e-17  3.43618134e+00]]
[-5.87777973  2.44159839  3.43618134]
[[-9.60135972e-01  2.79533388e-01  1.27790947e-17]
 [-2.79533388e-01  9.60135972e-01  9.71986784e-18]
 [-1.08951492e-17  3.74224514e-17  1.00000000e+00]]
u =  [[-1.04528089e+00]
 [-3.04322427e-01]
 [-1.18613317e-17]]


(0.5877779726875585, array([1.04528089e+00, 3.04322427e-01, 1.18613317e-17]))